name: storage_test
description: Aplicativo para contabilizar e gerenciar os itens armazenados.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  mobile_scanner: ^7.2.0
  logger: ^2.7.0
  supabase_flutter: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  assets:
     - assets/images/add_list.png
     - assets/images/barcode.png
     - assets/images/delete.png
     - assets/images/box.png
     - assets/images/list.png
     - assets/images/collect_list.png
  
  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
          weight: 700
 