name: storage_test
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  
  
  equatable: ^2.0.0

  
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  bloc: ^8.1.2
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  assets:
     - assets/images/add_list.png
     - assets/images/barcode.png
     - assets/images/delete.png
     - assets/images/box.png
     - assets/images/list.png
  
  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
          weight: 700
 